### ISSUE TITLE
V2 - SAT solver

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/pazusoba#26]
Satisfaction problem.

From my understanding, the algorithm will not stop until a certain condition is met. The condition can be all orbs must be connected with 2 other orbs if possible and bring orbs closer if possible. This is an interesting approach because you don't really need a heuristic and erase combo. This will lose the ability to do cascade puzzle and another issue is that the route might be too long. However, the speed is probably faster because we don't need to do heuristic and erase combo at all. This is more like a static analyser.

See below for my discussion with koduma san. It was a great conversation.

**Comment by koduma** [comment]
お久しぶりです。kodumaです。

パズドラソルバについて、良い情報が得られました。

SATソルバというものを用いて、数々のパズルが解けるそうです。(マッチ3パズルについては不明です)

私にとっては難しいので諦めましたが、HenryQuanさんのような高学歴な方であれば、可能かもしれません。

どうでしょうか？

**Comment by koduma** [comment]
https://snuke.hatenablog.com/entry/2015/04/03/014316

この方のブログがわかりやすいかもしれません。(私では無理でした)

**Comment by HenryQuan** [comment]
kodumaさん、お久しぶりです。お元気ですか。
情報ありがとうございました。

「SAT」という問題は聞いたことがあります。「N-Queens」とか「Sudoku」などの解決方法ですよね。

いえいえ、kodumaさんもすごい方ですよ。
私の専門はスマホアプリの開発で、アルゴリズムはすごく苦手です。
ですが、すごい @codythecoder 先輩がいます！

これはとてもいいアイデアだと思います。最後は確定最大コンボですね。そして、スピードも速いと思います。唯一の問題はルートが長いかもしれません。後で、試してみます！

@codythecoder 先輩は機械学習という魔法がつかえますので、魔法でソルバーを改善します！

**Comment by koduma** [comment]
HenryQuanさん、返信ありがとうございます。なんとか元気です！

機械学習はいい方法ですね。HenryQuanさんはその方向なのですね。

成果があったら、もしよろしければbenchmarkの方に結果を教えていただきたいです！

**Comment by HenryQuan** [comment]
kodumaさん、私も元気です！
はい、もちろんですよ。

機械学習は@codythecoder 先輩のおアイデアですよ。
ニューラルネットワークという方法を使って、10歩以内のすべての盤面を見て、
パタンを見つけるかもしれないをおっしゃいました。
私も理解できせん。さすがを私の先輩ですね！

私もkodumaさんみたいに「solver_sat.cpp」とか色んなバージョンを作って、試してみます。
成果があったら、kodumaさんと話します。

ところで、kodumaさんはパズドラをやっていますか。
私は最近、ランク９００超えました。１０００に参ります！

**Comment by koduma** [comment]
HenryQuanさんが元気で良かったです！

twitterの日本時間0時に"パズドラ定石メーカー"というサイトで、有志で確定最大コンボをいかに少ない手数で求めるかと競ってます。@ja_mmkさんという方が一番強いと思います。興味があれば是非参加してください！

satソルバについて考慮していただき、ありがとうございます。

パズドラはやったことはあるのですが、実は私は3コンボ程度しかできないです。ランクは100くらいですorz

**Comment by HenryQuan** [comment]
パズドラ定石メーカーですか。
ああ、kodumaさんのTwitterのあれですか。少ない手数で求めるのは面白そうですね。
それに、ja_mmkさんすごいですね、kodumaさんのソルバーを勝てることは。
日本時間の０時は流石に無理ですが、起きたら試したみます！

いえいえ、情報ありがとうございます。
パズドラソルバーの同志ですから。

そうですか。私は２０１４年から、今はＴＯＰ５％のプレイヤーかもしれません。
課金力は足りないから、いいモンスターがちょっと少ないですね。。。
ソルバーみたいなパズルができますが、考える時間はパズルより長いです。

パズそばはもう私を超えました。
私七年間の経験はマシンと比べると少ないですよね。
どんな未来を待つのが楽しみです。

**Comment by koduma** [comment]
twitterの投稿日時が遅くても、手数が短ければ上位という評価になると思います！

パズそば凄いですね。
私もマシンは人間より強いかもと考えています。

機械学習で未来を切り開いていってくださいね。
私の古典的プログラミングより有望だと思います。

**Comment by HenryQuan** [comment]
それは安心しました。

パズそばはもう私のパズル先生です。あの7x6十字落としパズルは私たちにとって新しい世界です。 

私も古典的なプログラマーですよ。Cは初のプログラミング言語でした。機械学習は人間の未知の領域に届けます。きっと、未来があると信じています。

今日、とても良い話しになりました。
そうして、今日はもう失礼いたします。
今後もよろしくお願いします！

またTwitterで

**Comment by koduma** [comment]
はい、よろしくお願いします！
